"""
Code Processor Module

Handles extraction, fixing, and validation of LLM-generated code.
Provides utilities for post-processing generated Python code.
"""

import ast
import io
import logging
import re
import tokenize
from typing import List, Set, Tuple

logger = logging.getLogger(__name__)


class CodeProcessor:
    """
    Processes LLM-generated code: extraction, fixing, and validation.

    Handles common LLM output issues:
    - Code extraction from <code> tags
    - Unicode character cleanup
    - Bytes literal fixing
    - Regex string conversion
    - Import validation
    - Class name correction
    """

    def __init__(self, allowed_imports: Set[str]):
        """
        Initialize the code processor.

        Args:
            allowed_imports: Set of allowed import module names
        """
        self._allowed_imports = allowed_imports

    def extract_code(self, response: str) -> str:
        """
        Extract code from <code> tags with robust fallback handling.

        Handles chain-of-thought responses that have <analysis> before <code>.
        Only extracts the <code> section, ignoring analysis.

        Args:
            response: Raw LLM response text

        Returns:
            Extracted and cleaned Python code
        """
        response = re.sub(
            r"<analysis>.*?</analysis>", "", response, flags=re.DOTALL | re.IGNORECASE
        )

        code = self._extract_code_block(response)
        code = self._strip_markup(code)
        return self._remove_commentary_lines(code)

    def _extract_code_block(self, response: str) -> str:
        """Extract the code block from tags or return raw response."""
        pattern = r"<code[^>]*>(.*?)</code>"
        matches = re.findall(pattern, response, re.DOTALL | re.IGNORECASE)

        if matches:
            return str(max(matches, key=len)).strip()

        code_start = re.search(r"<code[^>]*>", response, re.IGNORECASE)
        if code_start:
            return response[code_start.end() :]

        return response

    @staticmethod
    def _strip_markup(code: str) -> str:
        """Remove markdown fences and residual code tags."""
        code = re.sub(r"```[\w]*\s*\n?", "", code)
        code = re.sub(r"\n?```\s*$", "", code)
        code = re.sub(r"\n?```\s*\n", "\n", code)
        code = re.sub(r"</?code[^>]*>", "", code, flags=re.IGNORECASE)
        return code

    @staticmethod
    def _remove_commentary_lines(code: str) -> str:
        """Remove LLM commentary lines that are not valid Python."""
        lines = code.split("\n")
        cleaned_lines = []
        for line in lines:
            stripped = line.strip()
            if stripped.startswith("!"):
                continue
            if stripped.startswith("DO NOT EDIT") or stripped.startswith(
                "generated by"
            ):
                continue
            if stripped.startswith("Note:") or stripped.startswith("Note that"):
                continue
            if stripped.startswith("Since ") and not stripped.startswith("Since("):
                continue
            if stripped.startswith("This endpoint") or stripped.startswith("This is"):
                continue
            if stripped.startswith("We ") and (
                "test" in stripped.lower() or "endpoint" in stripped.lower()
            ):
                continue
            if stripped.startswith("STEP ") and ":" in stripped:
                continue
            if stripped.startswith("Method:") or stripped.startswith("Path:"):
                continue
            if stripped.startswith("Required:") or stripped.startswith("Optional:"):
                continue
            cleaned_lines.append(line)

        return "\n".join(cleaned_lines).strip()

    def fix_class_name(
        self, code: str, expected_class_name: str, scenario_type: str
    ) -> str:
        """
        Fix class name in generated code to match expected naming convention.

        Args:
            code: Generated Python code
            expected_class_name: Base class name expected
            scenario_type: Type of scenario (positive, negative, security)

        Returns:
            Code with corrected class name
        """
        scenario_suffix = f"{scenario_type.capitalize()}Workflow"
        expected_full_name = f"{expected_class_name}{scenario_suffix}"

        from devdox_ai_locust.utils.constants import WORKFLOW_CLASS_RE

        match = WORKFLOW_CLASS_RE.search(code)

        if match:
            actual_class_name = match.group(1)
            if actual_class_name != expected_full_name:
                logger.debug(
                    f"Fixing class name: {actual_class_name} -> {expected_full_name}"
                )
                code = re.sub(
                    rf"\bclass\s+{re.escape(actual_class_name)}\s*\(",
                    f"class {expected_full_name}(",
                    code,
                )

        return code

    def sanitize_unicode(self, code: str) -> str:
        """
        Remove non-ASCII characters from generated code.

        Args:
            code: Generated Python code

        Returns:
            Code with only ASCII characters
        """
        cleaned_lines = []
        for line in code.split("\n"):
            cleaned = "".join(c for c in line if ord(c) < 128)
            cleaned_lines.append(cleaned)
        return "\n".join(cleaned_lines)

    def fix_bytes_literals(self, code: str) -> str:
        """
        Fix bytes literals containing non-ASCII characters.

        Converts b'tëst' to 'tëst'.encode('utf-8').

        Args:
            code: Generated Python code

        Returns:
            Code with fixed bytes literals
        """

        def fix_single_quoted(match: re.Match[str]) -> str:
            content = match.group(1)
            try:
                content.encode("ascii")
                return match.group(0)
            except UnicodeEncodeError:
                return f"'{content}'.encode('utf-8')"

        def fix_double_quoted(match: re.Match[str]) -> str:
            content = match.group(1)
            try:
                content.encode("ascii")
                return match.group(0)
            except UnicodeEncodeError:
                return f"\"{content}\".encode('utf-8')"

        single_quote_pattern = r"b'((?:[^'\\]|\\.)*)'"
        double_quote_pattern = r'b"((?:[^"\\]|\\.)*)"'

        code = re.sub(single_quote_pattern, fix_single_quoted, code)
        code = re.sub(double_quote_pattern, fix_double_quoted, code)

        return code

    def fix_regex_strings(self, code: str) -> str:
        """
        Convert strings with regex escape sequences to raw strings.

        Converts "\\d" to r"\\d" to avoid SyntaxWarnings in Python 3.12+.

        Args:
            code: Generated Python code

        Returns:
            Code with raw strings for regex patterns
        """
        from devdox_ai_locust.utils.constants import PROBLEMATIC_ESCAPES_RE

        problematic_escapes = PROBLEMATIC_ESCAPES_RE

        try:
            tokens = list(tokenize.generate_tokens(io.StringIO(code).readline))
        except tokenize.TokenError:
            logger.debug(
                "Tokenization failed in fix_regex_strings, returning unchanged"
            )
            return code

        replacements = self._find_regex_replacements(tokens, problematic_escapes)

        if not replacements:
            return code

        return self._apply_replacements(code, replacements)

    def _find_regex_replacements(
        self, tokens: List[tokenize.TokenInfo], problematic_escapes: re.Pattern[str]
    ) -> List[Tuple[int, int, int, int, str, str]]:
        """Find string tokens that need regex raw-string conversion."""
        replacements = []

        for tok in tokens:
            if tok.type != tokenize.STRING:
                continue

            string_val = tok.string

            if string_val.startswith(
                ('r"', "r'", 'R"', "R'", 'br"', "br'", 'rb"', "rb'")
            ):
                continue
            if string_val.startswith(("b'", 'b"', "B'", 'B"')):
                continue
            if string_val.startswith(('"""', "'''")):
                continue

            try:
                parsed = ast.literal_eval(string_val)
                if not isinstance(parsed, str):
                    continue
            except (ValueError, SyntaxError):
                continue

            if not problematic_escapes.search(string_val):
                continue

            quote = '"' if string_val.startswith('"') else "'"
            inner = string_val[1:-1]
            new_string = f"r{quote}{inner}{quote}"

            replacements.append(
                (
                    tok.start[0],
                    tok.start[1],
                    tok.end[0],
                    tok.end[1],
                    string_val,
                    new_string,
                )
            )

        return replacements

    @staticmethod
    def _apply_replacements(code: str, replacements: List) -> str:
        """Apply token replacements to source code."""
        lines = code.split("\n")
        for start_row, start_col, end_row, end_col, old, new in reversed(replacements):
            if start_row == end_row:
                line = lines[start_row - 1]
                lines[start_row - 1] = line[:start_col] + new + line[end_col:]
            else:
                first_line = lines[start_row - 1]
                last_line = lines[end_row - 1]
                lines[start_row - 1] = first_line[:start_col] + new
                lines[end_row - 1] = last_line[end_col:]
                for i in range(start_row, end_row - 1):
                    lines[i] = ""

        return "\n".join(lines)

    def fix_missing_imports(self, code: str) -> str:
        """
        Add missing common imports that LLMs sometimes forget.

        Args:
            code: Generated Python code

        Returns:
            Code with necessary imports added
        """
        lines = code.split("\n")
        import_section_end = 0

        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith(("import ", "from ")):
                import_section_end = i + 1
            elif stripped and not stripped.startswith("#"):
                break

        has_random_choice = "random.choice(" in code
        has_random_import = any(
            "import random" in line or "from random" in line for line in lines
        )

        if has_random_choice and not has_random_import:
            lines.insert(import_section_end, "import random")
            logger.debug("Added missing 'import random'")

        has_datetime_use = "datetime." in code or "datetime(" in code
        has_datetime_import = any(
            "from datetime import" in line or "import datetime" in line
            for line in lines
        )

        if has_datetime_use and not has_datetime_import:
            lines.insert(import_section_end, "from datetime import datetime")
            logger.debug("Added missing 'from datetime import datetime'")

        return "\n".join(lines)

    def fix_isoformat_calls(self, code: str) -> str:
        """
        Fix isoformat() calls that use unsupported 'timespec' argument.

        Older versions or mock implementations may not support timespec.

        Args:
            code: Generated Python code

        Returns:
            Code with fixed isoformat calls
        """
        pattern = r'\.isoformat\(timespec=["\']seconds["\']\)'
        return re.sub(pattern, ".isoformat()", code)

    def validate_python_code(self, content: str) -> Tuple[bool, str]:
        """
        Validate Python syntax and check for suspicious imports.

        Args:
            content: Python code to validate

        Returns:
            Tuple of (is_valid, error_message)
        """
        try:
            compile(content, "<string>", "exec")
        except SyntaxError as e:
            return (
                False,
                f"Line {e.lineno}: {e.msg} - {e.text.strip() if e.text else ''}",
            )

        warnings = self.check_imports(content)
        if warnings:
            for warning in warnings:
                logger.warning(f"Suspicious import in generated code: {warning}")

        return True, ""

    def check_imports(self, content: str) -> List[str]:
        """
        Check for potentially problematic imports in generated code.

        Args:
            content: Python code to check

        Returns:
            List of warning messages for suspicious imports
        """
        warnings = []

        try:
            tree = ast.parse(content)
        except SyntaxError:
            return []

        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    module_name = alias.name.split(".")[0]
                    if module_name not in self._allowed_imports:
                        warnings.append(
                            f"import {alias.name} - module '{module_name}' not in allowed list"
                        )

            elif isinstance(node, ast.ImportFrom) and node.module:
                module_name = node.module.split(".")[0]
                if module_name not in self._allowed_imports:
                    warnings.append(
                        f"from {node.module} import ... - module '{module_name}' not in allowed list"
                    )

        return warnings

    def process_generated_code(
        self,
        response: str,
        expected_class_name: str,
        scenario_type: str,
    ) -> Tuple[str, bool, str]:
        """
        Full pipeline to process LLM-generated code.

        Extracts, fixes, and validates generated code.

        Args:
            response: Raw LLM response
            expected_class_name: Expected class name for the workflow
            scenario_type: Type of scenario (positive, negative, security)

        Returns:
            Tuple of (processed_code, is_valid, error_message)
        """
        code = self.extract_code(response)
        code = self.sanitize_unicode(code)
        code = self.fix_bytes_literals(code)
        code = self.fix_regex_strings(code)
        code = self.fix_missing_imports(code)
        code = self.fix_isoformat_calls(code)
        code = self.fix_class_name(code, expected_class_name, scenario_type)

        is_valid, error = self.validate_python_code(code)

        return code, is_valid, error
