name: "Swagger Test Generator"
description: "Generate Locust tests from a Swagger/OpenAPI URL"
on: [push]

jobs:
  swagger-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Locust tests
        uses: montymobile1/devdox-ai-locust@DV-48-add-git-hub-actions
        with:
          swagger_url: "https://petstore3.swagger.io/api/v3/openapi.json "
          output: "generated_tests"
          users: "15"
          spawn_rate: "3"
          run_time: "10m"
          together_api_key: ${{ secrets.TOGETHER_API_KEY }}
