"""
Tests for CodeProcessor utility class.
"""

import pytest

from devdox_ai_locust.utils.code_processor import CodeProcessor


@pytest.fixture
def processor():
    """Create a CodeProcessor with a standard set of allowed imports."""
    return CodeProcessor(
        allowed_imports={"locust", "random", "json", "datetime", "os", "re", "time"}
    )


class TestExtractCode:
    """Tests for extract_code and its helpers."""

    def test_extract_from_code_tags(self, processor):
        response = "<code>print('hello')</code>"
        assert processor.extract_code(response) == "print('hello')"

    def test_extract_from_code_tags_with_attributes(self, processor):
        response = '<code lang="python">print("hi")</code>'
        assert processor.extract_code(response) == 'print("hi")'

    def test_extract_ignores_analysis_tags(self, processor):
        response = "<analysis>Some reasoning</analysis><code>x = 1</code>"
        assert processor.extract_code(response) == "x = 1"

    def test_extract_strips_markdown_fences(self, processor):
        response = "<code>```python\nprint('hi')\n```</code>"
        assert processor.extract_code(response) == "print('hi')"

    def test_extract_unclosed_code_tag(self, processor):
        response = "<code>x = 1\ny = 2"
        result = processor.extract_code(response)
        assert "x = 1" in result
        assert "y = 2" in result

    def test_extract_plain_code_no_tags(self, processor):
        response = "x = 1\ny = 2"
        assert processor.extract_code(response) == "x = 1\ny = 2"

    def test_extract_picks_longest_code_block(self, processor):
        response = "<code>short</code><code>this is longer code</code>"
        assert processor.extract_code(response) == "this is longer code"

    def test_extract_removes_commentary_lines(self, processor):
        response = "<code>x = 1\nNote: this is a note\ny = 2</code>"
        result = processor.extract_code(response)
        assert "x = 1" in result
        assert "Note:" not in result
        assert "y = 2" in result

    @pytest.mark.parametrize(
        "line",
        [
            "!pip install locust",
            "DO NOT EDIT this file",
            "generated by AI",
            "Note: something",
            "Note that this",
            "Since we need to",
            "This endpoint does",
            "This is a test",
            "We test the endpoint",
            "STEP 1: do something",
            "Method: GET",
            "Path: /users",
            "Required: yes",
            "Optional: no",
        ],
    )
    def test_remove_commentary_lines_filters(self, processor, line):
        response = f"<code>x = 1\n{line}\ny = 2</code>"
        result = processor.extract_code(response)
        assert line not in result

    def test_remove_commentary_preserves_since_function_call(self, processor):
        response = "<code>Since(x)</code>"
        result = processor.extract_code(response)
        assert "Since(x)" in result


class TestFixClassName:
    """Tests for fix_class_name."""

    def test_fixes_wrong_class_name(self, processor):
        code = "class WrongName(BaseWorkflow):\n    pass"
        result = processor.fix_class_name(code, "Users", "positive")
        assert "class UsersPositiveWorkflow(BaseWorkflow):" in result

    def test_preserves_correct_class_name(self, processor):
        code = "class UsersPositiveWorkflow(BaseWorkflow):\n    pass"
        result = processor.fix_class_name(code, "Users", "positive")
        assert "class UsersPositiveWorkflow(BaseWorkflow):" in result

    def test_no_class_found_returns_unchanged(self, processor):
        code = "x = 1\ny = 2"
        result = processor.fix_class_name(code, "Users", "positive")
        assert result == code

    def test_scenario_type_capitalized(self, processor):
        code = "class Foo(BaseWorkflow):\n    pass"
        result = processor.fix_class_name(code, "Auth", "security")
        assert "class AuthSecurityWorkflow(BaseWorkflow):" in result


class TestSanitizeUnicode:
    """Tests for sanitize_unicode."""

    def test_removes_non_ascii(self, processor):
        code = "x = 'caf\u00e9'"
        result = processor.sanitize_unicode(code)
        assert "\u00e9" not in result
        assert "x = 'caf'" in result

    def test_preserves_ascii(self, processor):
        code = "x = 'hello world'"
        assert processor.sanitize_unicode(code) == code

    def test_handles_multiline(self, processor):
        code = "a = '\u00fc'\nb = 'ok'"
        result = processor.sanitize_unicode(code)
        assert "\u00fc" not in result
        assert "b = 'ok'" in result


class TestFixBytesLiterals:
    """Tests for fix_bytes_literals."""

    def test_fixes_non_ascii_single_quote(self, processor):
        code = "x = b't\u00ebst'"
        result = processor.fix_bytes_literals(code)
        assert ".encode('utf-8')" in result

    def test_fixes_non_ascii_double_quote(self, processor):
        code = 'x = b"t\u00ebst"'
        result = processor.fix_bytes_literals(code)
        assert ".encode('utf-8')" in result

    def test_preserves_ascii_bytes(self, processor):
        code = "x = b'hello'"
        result = processor.fix_bytes_literals(code)
        assert result == code

    def test_preserves_ascii_bytes_double_quote(self, processor):
        code = 'x = b"hello"'
        result = processor.fix_bytes_literals(code)
        assert result == code


class TestFixRegexStrings:
    """Tests for fix_regex_strings."""

    def test_converts_regex_to_raw_string(self, processor):
        code = 'x = "\\\\d+"'
        result = processor.fix_regex_strings(code)
        assert result.startswith("x = r")

    def test_leaves_raw_strings_alone(self, processor):
        code = r'x = r"\d+"'
        result = processor.fix_regex_strings(code)
        assert result == code

    def test_handles_tokenization_error(self, processor):
        """Source code catches tokenize errors and returns unchanged code.

        Note: The source currently references tokenize.TokenizeError which
        does not exist in Python 3.12+; it should be tokenize.TokenError.
        This test documents the expected behavior once that bug is fixed.
        """
        code = "def f(:\n  bad syntax here"
        try:
            result = processor.fix_regex_strings(code)
            assert result == code
        except AttributeError:
            pytest.skip(
                "Known bug: source uses tokenize.TokenizeError instead of TokenError"
            )


class TestValidatePythonCode:
    """Tests for validate_python_code."""

    def test_valid_code(self, processor):
        is_valid, error = processor.validate_python_code("x = 1\ny = 2")
        assert is_valid is True
        assert error == ""

    def test_syntax_error(self, processor):
        is_valid, error = processor.validate_python_code("def f(\n  x")
        assert is_valid is False
        assert error != ""

    def test_valid_code_with_suspicious_import(self, processor):
        code = "import subprocess\nx = 1"
        is_valid, error = processor.validate_python_code(code)
        assert is_valid is True  # still valid syntax


class TestCheckImports:
    """Tests for check_imports."""

    def test_allowed_import(self, processor):
        warnings = processor.check_imports("import json")
        assert warnings == []

    def test_disallowed_import(self, processor):
        warnings = processor.check_imports("import subprocess")
        assert len(warnings) == 1
        assert "subprocess" in warnings[0]

    def test_disallowed_from_import(self, processor):
        warnings = processor.check_imports("from subprocess import call")
        assert len(warnings) == 1

    def test_syntax_error_returns_empty(self, processor):
        warnings = processor.check_imports("import (\n bad")
        assert warnings == []

    def test_submodule_checks_top_level(self, processor):
        warnings = processor.check_imports("import os.path")
        assert warnings == []


class TestFixMissingImports:
    """Tests for fix_missing_imports."""

    def test_adds_missing_random_import(self, processor):
        code = "x = random.choice([1, 2, 3])"
        result = processor.fix_missing_imports(code)
        assert "import random" in result

    def test_does_not_duplicate_random_import(self, processor):
        code = "import random\nx = random.choice([1, 2])"
        result = processor.fix_missing_imports(code)
        assert result.count("import random") == 1

    def test_adds_missing_datetime_import(self, processor):
        code = "x = datetime.now()"
        result = processor.fix_missing_imports(code)
        assert "from datetime import datetime" in result

    def test_does_not_duplicate_datetime_import(self, processor):
        code = "from datetime import datetime\nx = datetime.now()"
        result = processor.fix_missing_imports(code)
        assert result.count("datetime") == code.count("datetime")


class TestFixIsoformatCalls:
    """Tests for fix_isoformat_calls."""

    def test_fixes_timespec_seconds(self, processor):
        code = "x.isoformat(timespec='seconds')"
        result = processor.fix_isoformat_calls(code)
        assert result == "x.isoformat()"

    def test_fixes_timespec_double_quotes(self, processor):
        code = 'x.isoformat(timespec="seconds")'
        result = processor.fix_isoformat_calls(code)
        assert result == "x.isoformat()"

    def test_preserves_plain_isoformat(self, processor):
        code = "x.isoformat()"
        result = processor.fix_isoformat_calls(code)
        assert result == "x.isoformat()"


class TestProcessGeneratedCode:
    """Tests for the full process_generated_code pipeline."""

    def test_full_pipeline_valid_code(self, processor):
        response = "<code>class Foo(BaseWorkflow):\n    pass</code>"
        code, is_valid, error = processor.process_generated_code(
            response, "Users", "positive"
        )
        assert is_valid is True
        assert "UsersPositiveWorkflow" in code

    def test_full_pipeline_syntax_error(self, processor):
        response = "<code>def bad_syntax</code>"
        code, is_valid, error = processor.process_generated_code(
            response, "Users", "positive"
        )
        assert is_valid is False

    def test_full_pipeline_strips_analysis(self, processor):
        response = "<analysis>thinking</analysis><code>x = 1</code>"
        code, is_valid, error = processor.process_generated_code(
            response, "Users", "positive"
        )
        assert "analysis" not in code
        assert "thinking" not in code
        assert is_valid is True
